"""add_sessions_and_job_session_id

Revision ID: bcaeffdc2ddd
Revises: a3f82c1d0e49
Create Date: 2026-05-22 18:14:45.762276

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bcaeffdc2ddd'
down_revision: Union[str, Sequence[str], None] = 'a3f82c1d0e49'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_token', sa.String(length=64), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_active', sa.DateTime(timezone=True), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_sessions_session_token'), 'user_sessions', ['session_token'], unique=True)
    op.add_column('docking_jobs', sa.Column('session_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_docking_jobs_session_id'), 'docking_jobs', ['session_id'], unique=False)
    op.create_foreign_key(None, 'docking_jobs', 'user_sessions', ['session_id'], ['id'])
    op.drop_index(op.f('uq_phytochemicals_pubchem_cid'), table_name='phytochemicals')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('uq_phytochemicals_pubchem_cid'), 'phytochemicals', ['pubchem_cid'], unique=True)
    op.drop_constraint(None, 'docking_jobs', type_='foreignkey')
    op.drop_index(op.f('ix_docking_jobs_session_id'), table_name='docking_jobs')
    op.drop_column('docking_jobs', 'session_id')
    # op.drop_index(op.f('ix_user_sessions_session_token'), table_name='user_sessions')
    op.execute("DROP INDEX IF EXISTS uq_phytochemicals_pubchem_cid")
    op.drop_table('user_sessions')
    # ### end Alembic commands ###
